MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
# libgit2 on conda-forge requires glibc >=2.14
c_stdlib_version:          # [linux]
  - 2.17                   # [linux]

libgit2:
  - '1.7'
  - '1.8'
