{% set version = "0.10.0" %}

package:
  name: cargo-c
  version: {{ version }}

source:
  url: https://github.com/lu-zero/cargo-c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 85230801f57c1f2b85d99fae3fc43f93080ecc0e3763a6af178fc5e6c218004b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - libcurl  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  host:
    - libcurl  # [not win]
    - libgit2
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - pkg-config  # [not win]

test:
  commands:
    - test -f ${PREFIX}/bin/cargo-cinstall  # [unix]
    - test -f ${PREFIX}/bin/cargo-cbuild    # [unix]
    - test -f ${PREFIX}/bin/cargo-ctest     # [unix]
    - test -f ${PREFIX}/bin/cargo-capi      # [unix]
    - test -f %LIBRARY_BIN%\cargo-cinstall.exe  # [win]
    - test -f %LIBRARY_BIN%\cargo-cbuild.exe    # [win]
    - test -f %LIBRARY_BIN%\cargo-ctest.exe     # [win]
    - test -f %LIBRARY_BIN%\cargo-capi.exe      # [win]
    - cargo-cinstall --version  # [build_platform == target_platform]
    - cargo-cbuild --version    # [build_platform == target_platform]
    - cargo-ctest --version     # [build_platform == target_platform]
    - cargo-capi --version      # [build_platform == target_platform]

about:
  home: https://github.com/lu-zero/cargo-c
  summary: build and install C-compatible libraries
  description: >
    cargo applet to build and install C-ABI compatible dynamic and static libraries.

    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
    - carterbox
